### ISSUE TITLE
Can BlocklyProp Launcher Intallation Issues

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyPropLauncher#100]
My system has BlocklyProp Launcher 0.10.0 installed. That installation was running on my system when I downloaded and installed version 0.11.0 of the Launcher. The installation proceeded without any incidents. There are two observations in this process that might confuse the user community. 

* The 0.11.0 installer does not appear to detect that a previous version is running. It continues with the installation. At the conclusion of the installation, the user is still running the 0.10.0 version. The user is likely to understand that the Launcher has been upgraded and not understand why the old version is still running.

* The 0.11.0 installer also does not appear to detect that a previous version of the Launcher has been installed and therefore makes no effort to update or replace the existing installation. At the conclusion of the 0.11.0 installation, there are now two BlocklyProp Launcher installations.

<img width="558" alt="Screen Shot 2020-02-26 at 10 58 19 AM" src="https://user-images.githubusercontent.com/8442260/75377694-36b6cb80-5887-11ea-9c35-b47628fc606b.png">

Spotlight continues to find the older version when launching the BlocklyProp Launcher from the Spotlight. Instead, the user needs to locate the new version in the Finder in order to launch it.

**Comment by PropGit** [comment]
Thanks @zfi.  This may be related to differences in how v0.10.0 was installed on your computer as that was before any official release for the Mac.  I will test this with the next version (using v0.11.0 already installed and installing a new one) to see if the problem persists and if there's something we can readily do about it.

**Comment by PropGit** [comment]
Verified, the new installer correctly upgrades both the Mac driver and the Installed BP Launcher (v0.11.0+).
