### ISSUE TITLE
Remove BlocklyProp button

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyPropLauncher#105]
@AndyLindsay @zfi
Discuss and decide if it's time to remove the BlocklyProp button and leave only the BlocklyProp Solo button.

**Comment by zfi** [comment]
We will post a banner message on the BlocklyProp site this afternoon to start the migration process to Solo. We can expect to disable new accounts sometime in April. I say that we remove the link and plan on a release in April to mirror the release of Solo 1.4.3.

**Comment by PropGit** [comment]
Note for clarity:

Removing the BlocklyProp button (and keeping only the BlocklyProp Solo button) will not prevent BlocklyProp Launcher from continuing to function with the current BlocklyProp system, so it's still a viable option for those who need to use BlocklyProp (rather than Solo) at any point during the transition.

**Comment by PropGit** [comment]
Done in v1.0.1, PR #112
