### ISSUE TITLE
Add timestamp to logging window

### ISSUE THREAD

**Issue by pjewald** [parallaxinc/BlocklyPropLauncher#72]
This is a request to insert an optional timestamp into log entries in the logging window.

08:29:00 Browser socket closing: 7

It's a bit difficult to track issues with long event horizons without the timestamp. As currently implemented, one has to constantly monitor the log output to find when a specific event occurs.

**Comment by PropGit** [comment]
This is done in v1.0.1 PR #110 

Instead of HH:MM:SS, it displays SSMMM (Seconds and Milliseconds) to save space and give relevant timing.
