### ISSUE TITLE
Split Open Browser button into two (for production-to-solo transition period)

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyPropLauncher#89]
As Solo is introduced and customers transition away from Production, the Launcher must support their needs (which may include using old and/or new system across customer base).

Split the **Open Browser** button into two buttons, each pointing to the different sites.

Also need to adjust the wording of the "Waiting to connect..." hint accordingly.

**Comment by PropGit** [comment]
Current (v0.10.0) looks like this:
![image](https://user-images.githubusercontent.com/1266318/69573517-1f5ffd80-0f7b-11ea-9292-688a176ce280.png)

Suggested:
- Move **Status:** area downward (and perhaps **Click:** area upward) to free up space for a new button.
- Move **Open Browser** downward (to become the 2nd such button) and change it to **BlocklyProp**.  No need to adjust the link; it should remain at:  https://blockly.parallax.com
- Add a new button above **BlocklyProp** button, called **BlocklyProp Solo** that uses link:  https://solo.parallax.com

**Comment by PropGit** [comment]
Consider adding a hint to each button to describe (in short phrase) what it is for.

BlocklyProp Solo hint = "No login required"
BlocklyProp hint = "Login required"

**Comment by PropGit** [comment]
Adjust Status hint that appears when moused-over "Waiting to connect..." message:
![image](https://user-images.githubusercontent.com/1266318/69574055-220f2280-0f7c-11ea-8465-342d4fcb079b.png)

Change it to read, "To connect: Open browser to desired site, then navigate to View/Edit project code"

**Comment by PropGit** [comment]
@zfi @AndyLindsay @Steph-Parallax I haven't updated the version number yet, but here are screenshots of the results of all the above changes.

NOTE: The **BlocklyProp Solo** button doesn't work with it set to https://solo.parallax.com because we don't yet have Solo set up for secure connection.

Normal View:
![image](https://user-images.githubusercontent.com/1266318/69649357-c8613380-1021-11ea-937c-1ee29fba7426.png)

BlocklyProp Solo button hint:
![image](https://user-images.githubusercontent.com/1266318/69649379-cdbe7e00-1021-11ea-9f7b-23e487702889.png)

BlocklyProp button hint:
![image](https://user-images.githubusercontent.com/1266318/69649388-d2833200-1021-11ea-9cf0-670737cc7211.png)

Status hint:
![image](https://user-images.githubusercontent.com/1266318/69649403-d747e600-1021-11ea-89dd-84b8654dd6e7.png)

**Comment by zfi** [comment]
That looks good to me. I'll get the SSL cert on Solo set up later today or in the morning.

**Comment by PropGit** [comment]
Done in PR #90
