### ISSUE TITLE
Installation on MacOS Catalina fails without override

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyPropLauncher#94]
The latest Launcher install package for MacOS is getting blocked by GateKeeper during installation because it does not appear to be notarized. There is a workaround described [here](https://support.apple.com/en-us/HT202491).

**Comment by PropGit** [comment]
Thanks @zfi - I meant to notarize it.  I'll check out the description too.

**Comment by zfi** [comment]
This is still happening with version 0.11.0 of the MacOS BlocklyProp Launcher package. 

<img width="430" alt="Screen Shot 2020-02-26 at 10 40 41 AM" src="https://user-images.githubusercontent.com/8442260/75376292-a6778700-5884-11ea-976f-f38206827b98.png">

**Comment by zfi** [comment]
Pressing the Control key while right-clicking the .pkg file in the Finder and selecting Open will present a slightly different dialog. The currently logged user must be an Administrator of the machine in order for this to work. That is likely a show-stopper for school districts.

<img width="426" alt="Screen Shot 2020-02-26 at 10 45 09 AM" src="https://user-images.githubusercontent.com/8442260/75376538-1259ef80-5885-11ea-8334-497aa226c132.png">

**Comment by PropGit** [comment]
This is being fixed in v0.11.1 and v0.11.2.

**Comment by PropGit** [comment]
Fixed via PR #103 and Release [v0.11.2](https://github.com/parallaxinc/BlocklyPropLauncher/releases/tag/v0.11.2)
